image: java:8-jdk

stages:
  - test
  - build

services:
  - 'mysql:5.5'
 
variables:
  MYSQL_DATABASE: newsdb
  MYSQL_URL: jdbc:mysql://localhost:3306/newsdb
  MYSQL_USER: root
  MYSQL_PASSWORD: mysql@2020
  MYSQL_ROOT_PASSWORD: mysql@2020